version: '3.4'

services:
  caffdb:
    container_name: caffdb
    environment:
      SA_PASSWORD: "Password123"
      ACCEPT_EULA: "Y"  
    restart: always
    ports:
      - "3500:1433"
    volumes:
      - caffdb:/var/opt/mssql